// Turns schema.json (every shared model under $defs, from launchpad_shared.export_schema)
// into src/schemas.ts: one zod schema + inferred type per model.
// json-schema-to-zod only converts the root schema, so each $def is converted on its own
// with its $refs inlined.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { jsonSchemaToZod } from "json-schema-to-zod";

const here = new URL(".", import.meta.url);
const { $defs } = JSON.parse(readFileSync(new URL("schema.json", here), "utf8"));

function inline(node) {
  if (Array.isArray(node)) return node.map(inline);
  if (node && typeof node === "object") {
    if (typeof node.$ref === "string") {
      const name = node.$ref.replace("#/$defs/", "");
      const { $ref, ...rest } = node;
      return inline({ ...$defs[name], ...rest });
    }
    return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, inline(v)]));
  }
  return node;
}

let out = "// Generated by packages/shared-ts/generate.mjs from launchpad_shared.models. Do not edit.\n";
out += 'import { z } from "zod";\n';
for (const name of Object.keys($defs).sort()) {
  out +=
    "\n" +
    jsonSchemaToZod(inline($defs[name]), {
      name: `${name}Schema`,
      module: "esm",
      type: name,
      noImport: true,
    }).trim() +
    "\n";
}

mkdirSync(new URL("src/", here), { recursive: true });
writeFileSync(new URL("src/schemas.ts", here), out);
console.log(`wrote src/schemas.ts (${Object.keys($defs).length} models)`);
