// Generated by packages/shared-ts/generate.mjs from firewatch_shared.models. Do not edit.
import { z } from "zod";

export const CitationSchema = z.object({ "kind": z.enum(["text","image","table","web"]), "page": z.union([z.number().int(), z.null()]).default(null), "uri": z.string() })
export type Citation = z.infer<typeof CitationSchema>

export const ClaimCheckSchema = z.object({ "claim": z.string(), "revision": z.union([z.string(), z.null()]).default(null), "sources": z.array(z.object({ "kind": z.enum(["text","image","table","web"]), "page": z.union([z.number().int(), z.null()]).default(null), "uri": z.string() })), "verdict": z.enum(["supported","unsupported","corrected"]) })
export type ClaimCheck = z.infer<typeof ClaimCheckSchema>

export const JournalistMatchSchema = z.object({ "journalist_id": z.string().uuid(), "reason": z.string(), "score": z.number() })
export type JournalistMatch = z.infer<typeof JournalistMatchSchema>

export const JudgeVerdictSchema = z.object({ "gaps": z.array(z.string()).default([]), "status": z.enum(["pass","fail"]) })
export type JudgeVerdict = z.infer<typeof JudgeVerdictSchema>

export const ProductFactSheetSchema = z.object({ "audience": z.string(), "key_features": z.array(z.string()), "launch_date": z.union([z.string().date(), z.null()]).default(null), "price_usd": z.number(), "product_line": z.union([z.string(), z.null()]).default(null), "product_name": z.string(), "promo": z.union([z.string(), z.null()]).describe("e.g. '20% off until Jun 30'").default(null), "sources": z.array(z.object({ "kind": z.enum(["text","image","table","web"]), "page": z.union([z.number().int(), z.null()]).default(null), "uri": z.string() })), "specs": z.record(z.string(), z.string()).default({}) })
export type ProductFactSheet = z.infer<typeof ProductFactSheetSchema>
